/* Main.ino file generated by New Project wizard
 *
 * Created	: Tue Sep 22 2026
 * Processor	: Arduino Uno
 * Compiler	: Arduino AVR (Proteus)
 * Programmer	: Abd Rahim Bin Kasiman
 */

#define led1	13
#define led2	12
#define led3	11
#define led4	10
#define pbAL	8
#define pbAH	9
#define timer	A1

#define d1(x)	digitalWrite(led1,x? HIGH:LOW)
#define d2(x)	digitalWrite(led2,x? HIGH:LOW)
#define d3(x)	digitalWrite(led3,x? HIGH:LOW)
#define d4(x)	digitalWrite(led4,x? HIGH:LOW)

void LEDs(uint8_t x)
{  d1(x&(1<<0));
   d2(x&(1<<1));
   d3(x&(1<<2));
   d4(x&(1<<3));
} 
 
void setup () 
{  pinMode(led1,OUTPUT);  pinMode(led2,OUTPUT);
   pinMode(led3,OUTPUT);  pinMode(led4,OUTPUT);
   pinMode(pbAL,INPUT);   pinMode(pbAH,INPUT);
   
   pinMode(timer,OUTPUT);
   digitalWrite(timer,LOW);
   
   Serial.begin(9600);
}

void loop() 
{  LEDs(10);
}
