/* Main.ino file generated by New Project wizard
 *
 * Created	: Tue Sep 22 2026
 * Processor	: Arduino Uno
 * Compiler	: Arduino AVR (Proteus)
 * Programmer	: Abd Rahim Bin Kasiman
 */

 #define led1	13
 #define led2	12
 #define led3	11
 #define led4	10
 #define pbAL	8
 #define pbAH	9
 #define timer	A1
 
void setup () 
{  pinMode(led1,OUTPUT);  pinMode(led2,OUTPUT);
   pinMode(led3,OUTPUT);  pinMode(led4,OUTPUT);
   pinMode(pbAL,INPUT);   pinMode(pbAH,INPUT);
   
   pinMode(timer,OUTPUT);
   digitalWrite(timer,LOW);
   
   Serial.begin(9600);
}

void loop() 
{  digitalWrite(led1,HIGH);	delay(500);
   digitalWrite(led1,LOW);	delay(500);
}


