/* Main.ino file generated by New Project wizard
 *
 * Created	: Tue Sep 22 2026
 * Processor	: Arduino Uno
 * Compiler	: Arduino AVR (Proteus)
 * Programmer	: Abd Rahim Bin Kasiman
 */
 
#include <LiquidCrystal.h>
const int rs=2, en=3, d4=4, d5=5, d6=6, d7=7;
LiquidCrystal lcd(rs, en, d4, d5, d6, d7);

#define led1	13
#define led2	12
#define led3	11
#define led4	10
#define pbAL	8
#define pbAH	9
#define timer	A1
#define clock	A2

#define d1(x)	digitalWrite(led1,x? HIGH:LOW)
#define d2(x)	digitalWrite(led2,x? HIGH:LOW)
#define d3(x)	digitalWrite(led3,x? HIGH:LOW)
#define d4(x)	digitalWrite(led4,x? HIGH:LOW)

void LEDs(uint8_t x)
{  d1(x&(1<<0));
   d2(x&(1<<1));
   d3(x&(1<<2));
   d4(x&(1<<3));
} 

uint8_t getPB(void)
{  uint8_t x=0;

   if(digitalRead(pbAL)==0) x |= 1<<0;
   if(digitalRead(pbAH)==1) x |= 1<<1;
   return x;
}
 
void setup () 
{  pinMode(led1,OUTPUT);  pinMode(led2,OUTPUT);
   pinMode(led3,OUTPUT);  pinMode(led4,OUTPUT);
   pinMode(pbAL,INPUT);   pinMode(pbAH,INPUT);
   
   pinMode(timer,OUTPUT);
   digitalWrite(timer,LOW);
   pinMode(timer,OUTPUT);
   pinMode(clock,OUTPUT);
   
   Serial.begin(9600);
   lcd.begin(16,2);
}

uint8_t cnt=0;
uint8_t seg=0;
void loop() 
{  if(getPB()==1)
   {  while(getPB()==1);
      delay(200);
      cnt++;
      if(cnt==2) cnt=0;
   }
   if(cnt==1) digitalWrite(timer,HIGH);
   if(cnt!=1) digitalWrite(timer,LOW);
   
   if(getPB()==2)
   {  digitalWrite(clock,HIGH);
      seg++;
      while(getPB()==2);
      delay(200);
      digitalWrite(clock,LOW);
      if(seg==21) seg=0;
   }
   
   lcd.setCursor(0,0); lcd.print("  HELLO WORLD!  ");
   lcd.setCursor(0,1); 
   lcd.print("An: "); 
   lcd.print(analogRead(A0));
   delay(100);
   lcd.setCursor(4,1); lcd.print("    ");
}
